import Head from 'next/head'
import Image from 'next/image'
import { Inter, Michroma,Epilogue } from '@next/font/google'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row w-screen h-screen bg-bgcolor' >
        <div className='flex flex-col h-screen w-1/2 justify-center items-start pl-[10%] ' >
          <p className={'text-[4vmax] text-secondary font-bold'} >Realtime Rewards</p>
          <p className='text-[4vmax] text-primary font-bold' >for staked Assets</p>
        </div>
      </div>
    </>
  )
}
